#spring.application.name=tutorpalvelu
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console
#spring.datasource.url=jdbc:h2:mem:testdb
#auth.jwt-secret=your-secret-key-must-be-at-least-256-bits-or-32-characters-long-for-hs256
#logging.level.hh_codebusters=DEBUG
#logging.level.org.springframework.security=DEBUG